#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi

  if [ -f "~/.config/homebrew/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global --file="$HOME/.config/homebrew/.Brewfile"
  fi

  if [ ! -d ~/.config/tmux/plugins/tpm ]; then
    git clone --depth 1 https://github.com/tmux-plugins/tpm ~/.config/.tmux/plugins/tpm
    (exec "~/.tmux/plugins/tpm/scripts/install_plugins.sh")
  fi

  if [ -d ~/.config/.tmux/plugins/tpm ]; then
    echo "Installing tmux plugins"
    (exec "~/.tmux/plugins/tpm/scripts/install_plugins.sh")

    tmux source ~/.config/tmux/tmux.conf
  fi

  if which WezTerm | grep -q "/opt/homebrew/bin/WezTerm"; then
    echo "Set terminal"

    tempfile=$(mktemp) \
    && curl -o $tempfile https://raw.githubusercontent.com/wez/wezterm/main/termwiz/data/wezterm.terminfo \
    && tic -x -o ~/.terminfo $tempfile \
    && rm $tempfile
  fi

  nvm install --lts
  npm install -g @anthropic-ai/claude-code
  npm install -g @google/gemini-cli

fi




