#!/bin/bash

set -e

DIVIDER="----------------------------------------------------------------------------"

if ! command -v brew > /dev/null; then
  echo "${DIVIDER}"
  echo "[YADM] Homebrew is not installed, exiting..."
  exit 1
fi

echo "${DIVIDER}"
echo "[YADM] Updating Homebrew"
brew update

if [ -f ~/.config/homebrew/Brewfile ]; then
  echo "${DIVIDER}"
  echo "[YADM] Updating homebrew bundle"
  brew bundle --file="$HOME/.config/homebrew/Brewfile"
fi

if [ ! -d ~/.tmux/plugins/tpm ]; then
  echo "${DIVIDER}"
  echo "[YADM] Tmux setup"
  git clone --depth 1 https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  ~/.tmux/plugins/tpm/scripts/install_plugins.sh
fi

if [ -d ~/.tmux/plugins/tpm ] && pgrep -q tmux; then
  echo "${DIVIDER}"
  echo "[YADM] Tmux reload config"
  tmux source ~/.config/tmux/tmux.conf
fi

if command -v wezterm > /dev/null; then
  echo "${DIVIDER}"
  echo "[YADM] Set terminal"

  tempfile=$(mktemp) \
  && curl -o $tempfile https://raw.githubusercontent.com/wez/wezterm/main/termwiz/data/wezterm.terminfo \
  && tic -x -o ~/.terminfo $tempfile \
  && rm $tempfile
fi

echo "[YADM] done."
