set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_status_modules_right "application session user host"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"

set-option -sa terminal-overrides ",xterm*:TC"
set -s escape-time 0
set -g mouse on


bind '|' split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-selection -x

run '~/.tmux/plugins/tpm/tpm'

